name: Send a Slack message
on: [push]
jobs:
  Send the slack message:
    runs-on: ubuntu-latest
      steps:
        - name: Notify slack
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          uses: pullreminders/slack-action@master
          with:
            args: '{\"channel\":\"C04HYQTG9SN\",\"text\":\"Hello world\"}'

